# Netlify configuration for Vite React app
[build]
  command = "npm run build"
  publish = "dist"

# Redirect all routes to index.html for SPA handling
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
